### ISSUE TITLE
dir-locals-directory-cache filling up with lots of entries for custom tramp methods

### ISSUE THREAD

**Issue by JasZhe** [jsadusk/tramp-hlo#4]
https://gist.github.com/jackrusher/36c80a2fd6a8fe8ddf46bc7e408ae1f9 I've been using this to add a custom gcssh tramp method to easily connect to gcp vm instances. 

There's a peculiar thing that happens where it seems like `tramp-hlo-dir-locals-find-file-cache-update` is constantly adding new values to dir-locals-directory-cache, and I'm not quite sure why.. 

It might be inserting the mtime incorrectly? 

For example I'm seeing:
```
("/gcssh:test-micro-vm:/home/myuser/project"
  /gcssh:test-micro-vm:/home/myuser/project (26919 6416 0 0))
```

The project itself has a .dir-locals.el file just to set eglot-server-programs and pyvenv-activate

whereas other entries seem to have values in the last 2 fields. I'm seeing this being computed a lot because of project-mode-line

I am able to reproduce this on emacs -Q after installing tramp-hlo, and enabling remote-dir-locals, navigating to say /gcssh:test-micro-vm:/home/myuser/project/main.py. 

Then it seems like every few commands I do (i.e. navigating lines) creates another entry. 

I'm wondering if it has something to do with the STAT_FORMAT or something in `tramp-hlo-dir-locals-find-file-cache-update-script`. I find it hard to debug cause I get a "Too deep - perhaps infinite loop in spec?" when trying to edebug-defun on `tramp-hlo-dir-locals-find-file-cache-update`

In the meanwhile I've simply removed the advice to 'dir-locals-find-file to still get some o the benefits of tramp-hlo. Thanks again for this package! 

Another note, for some files in a project, (seems to be non-eglot-managed files like .md files) vc doesn't seem to work either. When I do (project-current) I get nothing.

**Comment by jsadusk** [comment]
I found these same issues and I think I fixed them in release 0.0.2. Try it out and let me know if its fixed

**Comment by JasZhe** [comment]
@jsadusk still seeing the same issue after updating. Here's a small script I was using to reproduce on emacs -Q 

```
(defvar tramp-gcp-project "GCP_PROJECT")
(defvar tramp-gcp-zone "us-central1-c")

(require 'tramp)

(defun tramp-gcp--update-method ()
  "Re-register the `gcssh' TRAMP method using current project/zone."
  (let* (
         ;; placeholders in tramp.el in the "tramp-methods" docstring under "tramp-login-args"
         ;; these patterns are expanded by tramp-expand-script
         (spec `("gcssh"
                 (tramp-login-program "gcloud compute ssh")
                 (tramp-login-args
                  (("%h")
                   (,(concat "--project=" "\"" tramp-gcp-project "\""))
                   (,(concat "--zone="  "\"" tramp-gcp-zone "\""))
                   ("--tunnel-through-iap")))
                 (tramp-async-args           (("-q")))
                 (tramp-remote-shell         "/bin/sh")
                 (tramp-remote-shell-args    ("-c"))
                 (tramp-gw-args              (("-o" "GlobalKnownHostsFile=/dev/null")
                                              ("-o" "UserKnownHostsFile=/dev/null")
                                              ("-o" "StrictHostKeyChecking=no")))
                 (tramp-default-port         22))))
    ;; Remove any old copy first so we don’t accumulate duplicates.
    (setq tramp-methods (assoc-delete-all "gcssh" tramp-methods))
    (add-to-list 'tramp-methods spec)))

(tramp-gcp--update-method)

(package-refresh-contents)
(package-upgrade 'tramp)

(use-package tramp-hlo :ensure t :pin gnu :config (tramp-hlo-setup))

(setq enable-remote-dir-locals t)
(setq project-mode-line t) ;; enabling project mode line seems to cause problems since mode line gets updated frequently, triggering the project checking
```

Then find-file `/gcssh:my-micro-instance:/myproject/main.py`

I get a lot of these messages
```
Tramp: Inserting ‘/gcssh:my-micro-instance:/home/jz/myproject/.dir-locals.el’...done
```

I need to try and see if it's isolated to this gcssh thing i have or any general tramp method

**Comment by jsadusk** [comment]
Oh this might be caused by project-mode-line. I've found separate issues with project finding vc files. I have a change in the works to fix that, but i have limited time thanks to work and kids. That said, I'm not using gcp or gcssh so its possible that's also triggering issues. I'm going to run a few more tests to make sure dir-locals caching is working properly with straight ssh, and I'll add that to the ert tests.
Thanks for helping debug this.
